//! # Kernel Doctor Subsystem
//!
//! Autonomous diagnostic and repair engine for TylluanNexus.
//! Operates at the kernel level with access to all core subsystems.

use crate::registry::guild_process::GuildRegistry;
use crate::memory::hybrid::HybridMemory;
use crate::memory::silva::{SilvaDB, GraphNode};
use std::sync::Arc;
use tokio::sync::RwLock;
use serde::{Serialize, Deserialize};
use tracing::info;
use sysinfo::System;

/// A comprehensive health report generated by the Doctor.
#[derive(Debug, Serialize, Deserialize)]
pub struct DiagnosticReport {
    pub timestamp: String,
    pub status: String, // "healthy", "degraded", "critical"
    pub guilds: Vec<GuildHealth>,
    pub storage: StorageHealth,
    pub system: SystemHealth,
    pub config_valid: bool,
    pub suggestions: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct GuildHealth {
    pub name: String,
    pub running: bool,
    pub tools_count: usize,
    pub issues: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct StorageHealth {
    pub memory_db_ok: bool,
    pub silva_db_ok: bool,
    pub docs_count: usize,
    pub nodes_count: i64,
    pub memory_bytes: i64,
    pub silva_bytes: i64,
    pub recent_nodes: Vec<GraphNode>, // New: Sovereign Insights
}

/// System resource health for self-healing (like Windows/Linux).
/// Monitors physical limits to prevent crashes on "toaster" hardware.
#[derive(Debug, Serialize, Deserialize)]
pub struct SystemHealth {
    pub total_memory_mb: u64,
    pub used_memory_mb: u64,
    pub memory_percent: f32,
    pub cpu_usage_percent: f32,
    pub process_count: usize,
    pub thread_count: usize,
    pub status: String, // "ok", "warning", "critical"
    pub warnings: Vec<String>,
}

/// The Kernel Doctor subsystem.
#[derive(Clone)]
pub struct Doctor {
    registry: Arc<RwLock<GuildRegistry>>,
    memory: Arc<HybridMemory>,
    silva: Arc<SilvaDB>,
    curriculum: Arc<std::sync::Mutex<crate::curriculum::CurriculumLearner>>,
    errors_today: Arc<std::sync::atomic::AtomicU64>,
}

impl Doctor {
    /// Create a new Doctor with access to core subsystems.
    pub fn new(
        registry: Arc<RwLock<GuildRegistry>>,
        memory: Arc<HybridMemory>,
        silva: Arc<SilvaDB>,
        curriculum: Arc<std::sync::Mutex<crate::curriculum::CurriculumLearner>>,
    ) -> Self {
        Self {
            registry,
            memory,
            silva,
            curriculum,
            errors_today: Arc::new(std::sync::atomic::AtomicU64::new(0)),
        }
    }

    /// Get reference to SilvaDB
    pub fn silva(&self) -> Arc<SilvaDB> {
        self.silva.clone()
    }

    /// Get reference to HybridMemory
    pub fn memory(&self) -> Arc<HybridMemory> {
        self.memory.clone()
    }

    /// Get reference to CurriculumLearner
    pub fn curriculum(&self) -> Arc<std::sync::Mutex<crate::curriculum::CurriculumLearner>> {
        self.curriculum.clone()
    }

    /// Perform a deep diagnostic scan of the entire hub.
    pub async fn diagnose(&self) -> DiagnosticReport {
        info!("🩺 System diagnostic started...");
        
        let mut issues = Vec::new();
        let mut suggestions = Vec::new();

        // 1. Check Config Validity
        let config_valid = self.check_config_valid(&mut issues, &mut suggestions);

        // 2. Check Guilds
        let guilds = self.check_guilds(&mut issues, &mut suggestions).await;
        
        // 3. Check Storage
        let storage = self.check_storage(&mut issues, &mut suggestions).await;
        
        // 4. Check System Resources (like Windows/Linux self-monitoring)
        let system = self.check_system_resources(&mut issues, &mut suggestions);

        let status = if issues.is_empty() {
            "healthy".to_string()
        } else if issues.len() < 3 {
            "degraded".to_string()
        } else {
            "critical".to_string()
        };

        // Update error tracker
        self.errors_today.store(issues.len() as u64, std::sync::atomic::Ordering::Relaxed);

        DiagnosticReport {
            timestamp: chrono::Local::now().to_rfc3339(),
            status,
            guilds,
            storage,
            system,
            config_valid,
            suggestions,
        }
    }

    /// Fast path for real-time dashboard metrics (Dashboard/Office)
    pub async fn metrics(&self) -> serde_json::Value {
        let mut sys = System::new();
        sys.refresh_cpu_usage();
        sys.refresh_memory();
        
        // Quick CPU delta
        std::thread::sleep(std::time::Duration::from_millis(50));
        sys.refresh_cpu_usage();
        
        let cpu = sys.global_cpu_usage();
        let mem_total = sys.total_memory();
        let mem_used = sys.used_memory();
        let mem_pct = (mem_used as f32 / mem_total.max(1) as f32) * 100.0;
        
        let nodes = self.silva.node_count().await.unwrap_or(0);
        
        // Fetch curriculum stats for Overview counters
        let curr_stats = {
            let curr = self.curriculum.lock().unwrap_or_else(|e| e.into_inner());
            curr.get_stats()
        };
        
        let errs = self.errors_today.load(std::sync::atomic::Ordering::Relaxed);
        
        serde_json::json!({
            "cpu_percent": cpu,
            "memory_percent": mem_pct,
            "storage_bytes": self.silva.stats().await.map(|s| s.total_bytes).unwrap_or(0),
            "guilds_online": self.registry.read().await.guilds.values().filter(|g| g.is_running()).count(),
            "errors_today": errs,
            "nodes_count": nodes,
            "curriculum": curr_stats,
            "ts": chrono::Utc::now().timestamp_millis()
        })
    }

    /// Internal logic: Health check for all registered guilds.
    async fn check_guilds(&self, _global_issues: &mut Vec<String>, suggestions: &mut Vec<String>) -> Vec<GuildHealth> {
        // Use try_read_with_timeout to avoid deadlock if spawn_core_guilds holds write lock
        let reg = match tokio::time::timeout(
            std::time::Duration::from_secs(5),
            self.registry.read()
        ).await {
            Ok(reg) => reg,
            Err(_) => {
                suggestions.push("Guild check timed out - spawn in progress. Retry later.".to_string());
                return vec![];
            }
        };

        let mut healths = Vec::new();

        for status in reg.status_all() {
            let mut guild_issues = Vec::new();
            if !status.running && status.always_on {
                guild_issues.push("Critical: Always-on guild is not running.".to_string());
                suggestions.push(format!("Run 'doctor_repair(target=\"guild\", name=\"{}\")' to restart.", status.name));
            }

            healths.push(GuildHealth {
                name: status.name.clone(),
                running: status.running,
                tools_count: status.tools_count,
                issues: guild_issues,
            });
        }
        healths
    }

    /// Internal logic: Health check for SQLite databases.
    async fn check_storage(&self, global_issues: &mut Vec<String>, suggestions: &mut Vec<String>) -> StorageHealth {
        let memory_ok = self.memory.health_check().await.is_ok();
        let silva_ok = self.silva.health_check().await.is_ok();
        
        if !memory_ok {
            global_issues.push("CRITICAL: HybridMemory (tylluan.db) health check failed".to_string());
            suggestions.push("Check database file permissions or restore tylluan.db from backup".to_string());
        }
        if !silva_ok {
            global_issues.push("CRITICAL: SilvaDB (silva.db) health check failed".to_string());
            suggestions.push("Check file locks on data/silva.db or restore silva.db".to_string());
        }

        let docs_count = self.memory.document_count().await.unwrap_or(0) as usize;
        let nodes_count = self.silva.node_count().await.unwrap_or(0) as i64;
        
        let (memory_bytes, silva_bytes) = match (
            self.memory.stats().await,
            self.silva.stats().await,
        ) {
            (Ok(mem_stats), Ok(silva_stats)) => (mem_stats.total_bytes, silva_stats.total_bytes),
            _ => (0, 0),
        };

        // Fetch recent nodes for Intelligence section
        let recent_nodes = self.silva.get_recent_nodes(5).await.unwrap_or_default();

        StorageHealth {
            memory_db_ok: memory_ok,
            silva_db_ok: silva_ok,
            docs_count,
            nodes_count,
            memory_bytes,
            silva_bytes,
            recent_nodes,
        }
    }
    
    /// Internal logic: Health check for system resources (RAM, CPU, threads).
    /// Like Windows/Linux, monitors physical limits to prevent crashes.
    /// T05 Fix: Use selective refresh to reduce RAM footprint.
    fn check_system_resources(&self, issues: &mut Vec<String>, suggestions: &mut Vec<String>) -> SystemHealth {
        let mut sys = System::new();
        sys.refresh_cpu_usage();
        sys.refresh_memory();
        sys.refresh_processes(sysinfo::ProcessesToUpdate::All, true);
        
        // Accurate CPU requires two samples or at least one refresh on existing System
        // We do a small sleep to get a delta for CPU
        std::thread::sleep(std::time::Duration::from_millis(100));
        sys.refresh_cpu_usage();
        
        let total_memory = sys.total_memory();
        let used_memory = sys.used_memory();
        let memory_percent = (used_memory as f32 / total_memory as f32) * 100.0;
        
        let cpu_usage = sys.global_cpu_usage();
        
        let process_count = sys.processes().len();
        let thread_count = process_count * 2; // Approximate: 2 threads per process avg
        
        // Thresholds for "toaster" hardware (low-resource systems)
        let memory_warning = 80.0;
        let memory_critical = 95.0;
        let cpu_warning = 85.0;
        let cpu_critical = 98.0;
        
        let mut warnings = Vec::new();
        let mut status = "ok".to_string();
        
        // Memory check
        if memory_percent >= memory_critical {
            status = "critical".to_string();
            issues.push(format!("Memory CRITICAL: {}%", memory_percent as u32));
            suggestions.push("Immediately unload non-essential guilds or reduce AI model loading.".to_string());
            warnings.push(format!("🔥 MEMORY CRITICAL: {}% used ({}MB / {}MB)", 
                memory_percent as u32, used_memory / 1024 / 1024, total_memory / 1024 / 1024));
        } else if memory_percent >= memory_warning {
            if status != "critical" { status = "warning".to_string(); }
            warnings.push(format!("⚠️ Memory high: {}%", memory_percent as u32));
        }
        
        // CPU check
        if cpu_usage >= cpu_critical {
            if status != "critical" { status = "critical".to_string(); }
            issues.push(format!("CPU CRITICAL: {}%", cpu_usage as u32));
            warnings.push(format!("🔥 CPU CRITICAL: {}%", cpu_usage as u32));
        } else if cpu_usage >= cpu_warning {
            if status != "critical" { status = "warning".to_string(); }
            warnings.push(format!("⚠️ CPU high: {}%", cpu_usage as u32));
        }
        
        // Process/Thread limits (toaster specs)
        if process_count > 500 {
            warnings.push(format!("⚠️ High process count: {}", process_count));
        }
        
        SystemHealth {
            total_memory_mb: total_memory / 1024 / 1024,
            used_memory_mb: used_memory / 1024 / 1024,
            memory_percent,
            cpu_usage_percent: cpu_usage,
            process_count,
            thread_count,
            status,
            warnings,
        }
    }

    /// Attempt to repair a specific issue.
    pub async fn repair(&self, target: &str, name: Option<&str>) -> Result<String, String> {
        match target {
            "guild" => {
                if let Some(gname) = name {
                    info!("🩹 Repair: Restarting guild '{}'...", gname);
                    let mut reg = self.registry.write().await;
                    match reg.ensure_guild_running(gname).await {
                        Ok(_) => Ok(format!("✅ Guild '{}' successfully restarted.", gname)),
                        Err(e) => Err(format!("❌ Failed to repair guild '{}': {}", gname, e)),
                    }
                } else {
                    Err("Target 'guild' requires a 'name' parameter.".to_string())
                }
            }
            "storage" => {
                info!("🩹 Repair: Optimizing databases (VACUUM)...");
                let mut results = Vec::new();
                
                if let Err(e) = self.memory.vacuum().await {
                    results.push(format!("Memory error: {}", e));
                } else {
                    results.push("Memory optimized".to_string());
                }
                
                if let Err(e) = self.silva.vacuum().await {
                    results.push(format!("Silva error: {}", e));
                } else {
                    results.push("Silva optimized".to_string());
                }
                
                Ok(format!("✅ {}", results.join(", ")))
            }
            "benchmark" => {
                info!("🏃 Running quick performance benchmarks...");
                let mut output = String::new();
                
                // Quick string benchmark
                let start = std::time::Instant::now();
                let mut s = String::new();
                for _ in 0..10000 { s.push('x'); }
                let string_time = start.elapsed().as_millis();
                output.push_str(&format!("String alloc (10k): {}ms\n", string_time));
                
                // Quick hashmap benchmark
                let start = std::time::Instant::now();
                let mut map = std::collections::HashMap::new();
                for i in 0..10000 { map.insert(i, i * 2); }
                let hashmap_time = start.elapsed().as_millis();
                output.push_str(&format!("HashMap insert (10k): {}ms\n", hashmap_time));
                
                // Storage stats
                if let Ok(stats) = self.memory.stats().await {
                    output.push_str(&format!("Memory DB: {} bytes\n", stats.total_bytes));
                }
                if let Ok(stats) = self.silva.stats().await {
                    output.push_str(&format!("Silva DB: {} bytes\n", stats.total_bytes));
                }
                
                Ok(format!("✅ Benchmark results:\n{}", output))
            }
            _ => Err(format!("Unknown repair target: {}", target)),
        }
    }

    /// Internal logic: Validates loaded configuration files and paths.
    fn check_config_valid(&self, issues: &mut Vec<String>, suggestions: &mut Vec<String>) -> bool {
        match crate::config::TylluanConfig::load() {
            Ok(config) => {
                let db_path = std::path::Path::new(&config.memory.db_path);
                if let Some(parent) = db_path.parent()
                    && !parent.exists() {
                        issues.push("WARNING: Database directory does not exist".to_string());
                        suggestions.push(format!("Create directory: {}", parent.display()));
                        return false;
                    }
                
                let models_dir = std::path::Path::new("models");
                if !models_dir.exists() {
                    issues.push("WARNING: AI models directory not found".to_string());
                    suggestions.push("Run setup-models.ps1 or call kernel with --download-models to resolve.".to_string());
                }
                true
            }
            Err(e) => {
                issues.push(format!("CRITICAL: tylluan.toml configuration is invalid or corrupt: {}", e));
                suggestions.push("Verify that tylluan.toml has correct syntax and structure.".to_string());
                false
            }
        }
    }
}
