"""
SilvaDB utilities for Python guilds — direct node insertion.
M17-4 Drift Guard: summary/synthesis/agent_summary cannot be created through guilds.
"""

import sys
import sqlite3
import uuid
import json
import logging
from pathlib import Path
from typing import Optional, Dict, Any, List
from datetime import datetime

logger = logging.getLogger("tylluan-silva")

# Drift-sensitive types — auto-generated by internal cognitive modules.
# Guilds (Python) MUST NOT create these to prevent drift de consolidación.
DRIFT_SENSITIVE_TYPES = frozenset(["summary", "synthesis", "agent_summary"])

KERNEL_URL = "http://127.0.0.1:3030"
# In dev_mode=true, the token is ignored by the kernel but kept for protocol consistency
AUTH_TOKEN = "<TYLLUAN_TOKEN>" 


# LLMLingua compression logic
try:
    from llmlingua import PromptCompressor
    _compressor = None
    
    def get_compressor():
        global _compressor
        if _compressor is None:
            _compressor = PromptCompressor(
                model_name="microsoft/llmlingua-2-xlm-roberta-large-meetingbank",
                use_llmlingua2=True,
                device_map="cpu",
            )
        return _compressor
    
    def compress_for_storage(text: str) -> str:
        if len(text) < 300:  # Don't compress short texts
            return text
        try:
            compressor = get_compressor()
            result = compressor.compress_prompt(
                text, rate=0.4, force_tokens=["\n"]
            )
            compressed = result["compressed_prompt"]
            logger.info(f"📦 compressed episode: {len(text)}→{len(compressed)} chars")
            return compressed
        except Exception:
            return text  # Always fall back to original
            
except ImportError:
    def compress_for_storage(text: str) -> str:
        return _extractive_compress(text)
    
    def _extractive_compress(text: str, max_sentences: int = 8) -> str:
        """Pure Python extractive fallback — no dependencies."""
        import re
        sentences = re.split(r'(?<=[.!?])\s+', text.strip())
        if len(sentences) <= max_sentences:
            return text
        # Score by position (first + last sentences most important)
        # + length (prefer medium-length sentences)
        scored = []
        for i, s in enumerate(sentences):
            pos_score = 1.0 if i < 2 or i >= len(sentences) - 2 else 0.5
            len_score = min(len(s) / 100, 1.0)
            scored.append((pos_score + len_score, i, s))
        top = sorted(scored, reverse=True)[:max_sentences]
        compressed = " ".join(s for _, i, s in sorted(top, key=lambda x: x[1]))
        logger.info(f"📦 compressed episode (extractive): {len(text)}→{len(compressed)} chars")
        return compressed


def get_silva_db_path() -> Path:
    root = Path(__file__).parent.parent.parent.resolve()
    return root / "data" / "silva.db"


def add_node(
    content: str,
    node_type: str = "document",
    tags: Optional[List[str]] = None,
    metadata: Optional[Dict[str, Any]] = None,
) -> Optional[str]:
    """Insert a node into SilvaDB. Returns node id or None on failure.
    M17-4 Drift Guard: rejects drift-sensitive types from guild/public paths."""
    if node_type in DRIFT_SENSITIVE_TYPES:
        logger.warning(f"DRIFT GUARD: node type '{node_type}' is drift-sensitive and cannot be created through guilds. Skipping.")
        return None
    content = compress_for_storage(content)
    silva_path = get_silva_db_path()
    if not silva_path.exists():
        return None

    try:
        conn = sqlite3.connect(str(silva_path))
        node_id = str(uuid.uuid4())
        now = datetime.now().isoformat()

        # Merge tags into metadata dict (schema has no tags column)
        meta: Dict[str, Any] = metadata or {}
        if tags:
            meta["tags"] = tags

        conn.execute(
            """INSERT INTO nodes (id, type, content, metadata, weight, created_at, updated_at)
               VALUES (?, ?, ?, ?, 1.0, ?, ?)""",
            (node_id, node_type, content, json.dumps(meta), now, now),
        )
        conn.commit()
        conn.close()
        return node_id
    except Exception as e:
        print(f"silva_utils: error adding node: {e}", file=sys.stderr)
        return None


def search_nodes(query: str, limit: int = 10) -> List[Dict[str, Any]]:
    """Full-text search over SilvaDB content."""
    silva_path = get_silva_db_path()
    if not silva_path.exists():
        return []

    try:
        conn = sqlite3.connect(str(silva_path))
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            """SELECT id, content, type, created_at
               FROM nodes
               WHERE content LIKE ?
               ORDER BY created_at DESC
               LIMIT ?""",
            (f"%{query}%", limit),
        ).fetchall()
        conn.close()
        return [
            {
                "id": row["id"],
                "content": row["content"][:200] + ("..." if len(row["content"]) > 200 else ""),
                "node_type": row["type"],
                "created_at": row["created_at"],
            }
            for row in rows
        ]
    except Exception as e:
        print(f"silva_utils: search error: {e}", file=sys.stderr)
        return []

def _http_post(endpoint: str, payload: dict) -> dict:
    """Helper for HTTP IPC with the kernel using standard library only."""
    import urllib.request
    url = f"{KERNEL_URL}{endpoint}"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {AUTH_TOKEN}"
    }
    body = json.dumps(payload).encode("utf-8")
    try:
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        logger.error(f"silva_utils IPC error: {e}")
        return {"ok": False, "error": str(e)}


def write_edge(source: str, predicate: str, target: str, metadata: dict = None) -> bool:
    """Write a knowledge triple as an edge in SilvaDB via HTTP IPC.
    
    Args:
        source: Subject node ID or name
        predicate: Relationship type (verb phrase)
        target: Object node ID or name
        metadata: Optional dict with confidence, model, etc.
    Returns:
        True on success, False on error (never raises)
    """
    payload = {
        "source": source,
        "target": target,
        "edge_type": predicate,
        "metadata": json.dumps(metadata or {})
    }
    resp = _http_post("/api/v1/silva/edge", payload)
    return resp.get("ok", False)


def add_edge_direct(source: str, predicate: str, target: str, metadata: dict = None) -> bool:
    """Write a knowledge triple directly to the SQLite silva.db database."""
    silva_path = get_silva_db_path()
    if not silva_path.exists():
        return False
    try:
        conn = sqlite3.connect(str(silva_path))
        conn.execute(
            """INSERT OR IGNORE INTO edges (source, target, type, metadata, weight)
               VALUES (?, ?, ?, ?, 1.0)""",
            (source, target, predicate, json.dumps(metadata or {})),
        )
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        logger.error(f"silva_utils: error adding edge: {e}")
        return False


def extract_triples_local(content: str) -> list[tuple[str, str, str]]:
    """Port of Rust triple_extractor — deterministic regex triples, no LLM."""
    patterns = [
        (" es ",    "es_un"),
        (" is ",    "es_un"),
        (" usa ",   "usa"),
        (" uses ",  "usa"),
        (" tiene ", "tiene"),
        (" has ",   "tiene"),
        (" -> ",    "relacionado_con"),
        (" → ",     "relacionado_con"),
    ]
    triples: list[tuple[str, str, str]] = []
    seen: set[str] = set()
    lower = content.lower()
    for sep, predicate in patterns:
        if len(triples) >= 3:
            break
        pos = lower.find(sep)
        if pos == -1:
            continue
        words_before = lower[:pos].split()
        subj = words_before[-1].strip(" .,;:") if words_before else ""
        rest = lower[pos + len(sep):]
        words_after = rest.split()
        obj = words_after[0].strip(" .,;:") if words_after else ""
        if not subj or not obj or len(subj) > 40 or len(obj) > 40:
            continue
        key = f"{subj}|{predicate}|{obj}"
        if key not in seen:
            seen.add(key)
            triples.append((subj, predicate, obj))
    return triples


def ensure_node_exists(node_id: str, node_type: str = "entity") -> bool:
    """Checks if a node exists, or creates a stub if missing."""
    silva_path = get_silva_db_path()
    if not silva_path.exists():
        return False
    try:
        conn = sqlite3.connect(str(silva_path))
        res = conn.execute("SELECT 1 FROM nodes WHERE id = ?", (node_id,)).fetchone()
        if not res:
            now = datetime.now().isoformat()
            conn.execute(
                "INSERT INTO nodes (id, type, content, weight, created_at, updated_at) VALUES (?, ?, ?, 1.0, ?, ?)",
                (node_id, node_type, node_id, now, now)
            )
            conn.commit()
        conn.close()
        return True
    except Exception:
        return False
