//! Node CRUD, embeddings, state mutations, and listing operations.
//! M17-4: Drift Guard — summary/synthesis/agent_summary cannot be created
//! through the public API. Internal modules (graph_rag, consensus, agent_memory)
//! use allow_drift=true to bypass.

use anyhow::Result;
use rusqlite::params;
use tracing::{info, warn};
use chrono::Utc;
use std::collections::HashMap;
use crate::memory::louvain::WeightedGraph;
use super::{GraphNode, NodeTrace};

fn read_timestamp(row: &rusqlite::Row, idx: usize) -> rusqlite::Result<Option<String>> {
    match row.get::<_, rusqlite::types::Value>(idx)? {
        rusqlite::types::Value::Text(s) => Ok(Some(s)),
        rusqlite::types::Value::Integer(i) => {
            let secs = if i > 1_000_000_000_000 { i / 1000 } else { i };
            Ok(Some(chrono::DateTime::from_timestamp(secs, 0)
                .map(|d| d.format("%Y-%m-%d %H:%M:%S").to_string())
                .unwrap_or_else(|| secs.to_string())))
        }
        rusqlite::types::Value::Null => Ok(None),
        _ => Ok(None),
    }
}/// Options for node writes that go beyond the basic upsert.
pub struct NodeWriteOptions<'a> {
    pub valid_from: Option<i64>,
    pub valid_until: Option<i64>,
    pub allow_drift: bool,
    pub provenance: &'a str,
    /// J-8: hierarchical scope tag, e.g. "user:alice/session:s1/agent:claude".
    /// None = unscoped (visible regardless of scope filtering).
    pub owner_scope: Option<&'a str>,
    /// M40-P4: explicit source — where the knowledge originated
    /// (e.g. "user_conversation", "documentation", "observation").
    pub source: Option<&'a str>,
    /// M40-P4: explicit author — which agent/user created this
    /// (e.g. "tylluan", "agent:deep", "user:forja").
    pub author: Option<&'a str>,
    /// M40-P4: link to original evidence (URL, file path, commit hash).
    pub evidence_url: Option<&'a str>,
}

impl<'a> NodeWriteOptions<'a> {
    pub fn new(provenance: &'a str) -> Self {
        Self { valid_from: None, valid_until: None, allow_drift: false, provenance, owner_scope: None, source: None, author: None, evidence_url: None }
    }
    pub fn drift_allowed(mut self, yes: bool) -> Self {
        self.allow_drift = yes;
        self
    }
    pub fn valid_until(mut self, until: Option<i64>) -> Self {
        self.valid_until = until;
        self
    }

    pub fn valid_from(mut self, from: Option<i64>) -> Self {
        self.valid_from = from;
        self
    }
    pub fn owner_scope(mut self, scope: Option<&'a str>) -> Self {
        self.owner_scope = scope;
        self
    }
    /// M40-P4: set explicit source (where knowledge originated).
    pub fn source(mut self, s: Option<&'a str>) -> Self {
        self.source = s;
        self
    }
    /// M40-P4: set explicit author (which agent/user created this).
    pub fn author(mut self, a: Option<&'a str>) -> Self {
        self.author = a;
        self
    }
    /// M40-P4: set evidence URL (link to original evidence).
    pub fn evidence_url(mut self, url: Option<&'a str>) -> Self {
        self.evidence_url = url;
        self
    }
}

/// Group of edges by (source, type) — used in supersession logic.
type EdgeGroupMap = std::collections::HashMap<(String, String), Vec<(String, Option<i64>)>>;

/// Node types that are generated by internal cognitive modules (GraphRAG, Consensus, AgentMemory).
/// These MUST NOT be created through the public API (HTTP ingest, tylluan_remember, guilds)
/// to prevent "drift de consolidación" — auto-generated summaries being re-ingested as facts.
pub const DRIFT_SENSITIVE_TYPES: &[&str] = &["summary", "synthesis", "agent_summary"];

impl super::SilvaDB {
    fn normalize_topic_key(&self, topic: &str) -> String {
        topic.trim()
            .replace("\\\"", "")
            .replace("\"", "")
            .to_string()
    }

    /// Upsert a node through the PUBLIC API (drift-guarded).
    /// Rejects drift-sensitive types (summary, synthesis, agent_summary).
    /// Internal cognitive modules call `upsert_node_with_validity` directly with allow_drift=true.
    pub async fn upsert_node(
        &self,
        id: &str,
        node_type: &str,
        content: &str,
        metadata: &str,
    ) -> Result<()> {
        self.upsert_node_with_validity(id, node_type, content, metadata, NodeWriteOptions::new("unverified")).await
    }

    /// Upsert a node with explicit provenance marking.
    /// Provenance values: "user_direct", "agent_generated", "federation_peer", "guild_output", "unverified"
    pub async fn upsert_node_with_provenance(
        &self,
        id: &str,
        node_type: &str,
        content: &str,
        metadata: &str,
        provenance: &str,
    ) -> Result<()> {
        self.upsert_node_with_validity(id, node_type, content, metadata, NodeWriteOptions::new(provenance)).await
    }

    /// Upsert a node with optional temporal validity and drift guard bypass.
    /// - `opts.allow_drift = false` (default for public API): rejects summary/synthesis/agent_summary
    /// - `opts.allow_drift = true` (internal modules only): allows all types
    /// - `opts.provenance` marks the origin of this node for trust-at-read filtering (M34-P0)
    pub async fn upsert_node_with_validity(
        &self,
        id: &str,
        node_type: &str,
        content: &str,
        metadata: &str,
        opts: NodeWriteOptions<'_>,
    ) -> Result<()> {
        let NodeWriteOptions { valid_from, valid_until, allow_drift, provenance, owner_scope, source, author, evidence_url } = opts;
        if !allow_drift && DRIFT_SENSITIVE_TYPES.contains(&node_type) {
            anyhow::bail!(
                "DRIFT GUARD: node type '{node_type}' is drift-sensitive and cannot be created through the public API. \
                 Use allow_drift=true for internal paths (graph_rag, consensus, agent_memory)."
            );
        }

        let parsed_meta = serde_json::from_str::<serde_json::Value>(metadata).ok();
        let topic_key: Option<String> = if metadata.trim().starts_with('{') {
            parsed_meta.as_ref().and_then(|v| v.get("topic").and_then(|t| t.as_str().map(|s| self.normalize_topic_key(s))))
        } else if metadata.trim().starts_with('"') {
            if let Ok(s) = serde_json::from_str::<String>(metadata) {
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(&s) {
                    v.get("topic").and_then(|t| t.as_str().map(|s| self.normalize_topic_key(s)))
                } else { None }
            } else { None }
        } else { None };
        // Extract federation_source from metadata to store in the proper SQL column (M11-C)
        let federation_source: Option<String> = parsed_meta
            .as_ref()
            .and_then(|v| v.get("federation_source").and_then(|s| s.as_str().map(String::from)));

        tokio::task::block_in_place(|| {
            let mut conn = self.conn.blocking_lock();
            // Compute deterministic content hash (SHA-256) for SH-conflict detection (paper 1.3)
            use sha2::Digest;
            let content_hash = format!("{:x}", sha2::Sha256::digest(content.as_bytes()));
            // Default valid_from to now if not explicitly set
            let vf = valid_from.unwrap_or_else(|| Utc::now().timestamp());
            // M31 audit fix: the node row and its FTS5 mirror were two separate
            // execute() calls with no transaction -- a crash between them left
            // the FTS index permanently out of sync with the real node content.
            let tx = conn.transaction()?;
            tx.execute(
                "INSERT INTO nodes (id, type, content, metadata, weight, protected, conflicted, topic_key, updated_at, valid_from, valid_until, shareable, federation_source, content_hash, provenance, owner_scope, source, author, evidence_url)
                 VALUES (?1, ?2, ?3, ?4, 1.0, 0, 0, ?5, CURRENT_TIMESTAMP, ?6, ?7, 0, ?8, ?9, ?10, ?11, ?12, ?13, ?14)
                 ON CONFLICT(id) DO UPDATE SET
                    content = excluded.content,
                    metadata = excluded.metadata,
                    weight = CASE
                        WHEN nodes.type = 'identity' OR nodes.protected = 1 THEN nodes.weight
                        ELSE MAX(nodes.weight, excluded.weight)
                    END,
                    protected = excluded.protected,
                    topic_key = COALESCE(excluded.topic_key, nodes.topic_key),
                    valid_from = COALESCE(excluded.valid_from, nodes.valid_from),
                    valid_until = COALESCE(excluded.valid_until, nodes.valid_until),
                    shareable = excluded.shareable,
                    federation_source = COALESCE(excluded.federation_source, nodes.federation_source),
                    content_hash = COALESCE(excluded.content_hash, nodes.content_hash),
                    provenance = excluded.provenance,
                    owner_scope = COALESCE(excluded.owner_scope, nodes.owner_scope),
                    source = COALESCE(excluded.source, nodes.source),
                    author = COALESCE(excluded.author, nodes.author),
                    evidence_url = COALESCE(excluded.evidence_url, nodes.evidence_url),
                    updated_at = CURRENT_TIMESTAMP",
                params![id, node_type, content, metadata, topic_key, vf, valid_until, federation_source, content_hash, provenance, owner_scope, source, author, evidence_url],
            )?;
            // Sync FTS5 index within the same transaction
            if let Ok(rowid) = tx.query_row("SELECT rowid FROM nodes WHERE id = ?1", params![id], |r| r.get::<_, i64>(0)) {
                let _ = tx.execute(
                    "INSERT INTO nodes_fts(rowid, id, content, metadata) VALUES (?1, ?2, ?3, ?4)",
                    params![rowid, id, content, metadata],
                );
            }
            tx.commit()?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Get a node by ID. Applies lazy weight decay before returning.
    pub async fn get_node(&self, id: &str) -> Result<Option<GraphNode>> {
        self.apply_node_decay(id).await.map_err(|e| warn!("🌲 node_decay failed for '{}': {}", id, e)).ok();
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs() as i64;
            let _ = conn.execute(
                "UPDATE nodes SET access_count = access_count + 1, last_accessed = ?1 WHERE id = ?2",
                params![now, id],
            );
            self.get_node_sync(id, &conn)
        })
    }

    /// M40-P4: read a node's confidence score (default 1.0, fully confident, for
    /// nodes written before this column existed or missing entirely). Deliberately
    /// NOT added to `GraphNode` itself -- that struct is constructed at ~20 call
    /// sites across silva/*.rs, and confidence only matters where an agent-facing
    /// consumer (tylluan_recall) needs to explain "why do you believe this", not
    /// every internal graph traversal. Fetched on demand instead.
    pub async fn get_confidence(&self, id: &str) -> f64 {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            conn.query_row("SELECT confidence FROM nodes WHERE id = ?1", params![id], |r| r.get(0))
                .unwrap_or(1.0)
        })
    }

    /// M40-P4 (second cut): read a node's explicit source/author/evidence.
    /// Same rationale as `get_confidence` — fetched on demand where an
    /// agent-facing consumer needs to explain provenance, not at every
    /// internal graph traversal. Returns (source, author, evidence_url),
    /// all None for nodes written before v20 or without these fields set.
    pub async fn get_source_info(&self, id: &str) -> (Option<String>, Option<String>, Option<String>) {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            conn.query_row(
                "SELECT source, author, evidence_url FROM nodes WHERE id = ?1",
                params![id],
                |r| Ok((r.get(0)?, r.get(1)?, r.get(2)?)),
            ).unwrap_or((None, None, None))
        })
    }

    /// Synchronous internal helper to get a node by ID.
    pub(crate) fn get_node_sync(&self, id: &str, conn: &rusqlite::Connection) -> Result<Option<GraphNode>> {
        let mut stmt = conn.prepare(
            "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, valid_from, valid_until, shareable, content_hash, provenance FROM nodes WHERE id = ?1",
        )?;
        let mut rows = stmt.query(params![id])?;
        if let Some(row) = rows.next()? {
            Ok(Some(GraphNode {
                id: row.get(0)?,
                node_type: row.get(1)?,
                content: row.get(2)?,
                metadata: row.get(3)?,
                weight: row.get(4)?,
                protected: row.get::<_, i32>(5)? != 0,
                conflicted: row.get::<_, i32>(6)? != 0,
                topic_key: row.get(7)?,
                created_at: read_timestamp(row, 8)?,
                updated_at: read_timestamp(row, 9)?,
                valid_from: row.get(10)?,
                valid_until: row.get(11)?,
                shareable: row.get::<_, i32>(12)? != 0,
                content_hash: row.get::<_, String>(13).unwrap_or_default(),
                provenance: row.get::<_, String>(14).unwrap_or_default(),
                last_touched: Utc::now(),
            }))
        } else {
            Ok(None)
        }
    }

    /// Lightweight freshness info for deterministic conflict resolution (paper 1.3).
    /// Returns (content_hash, protected, updated_at) without loading the full node.
    pub async fn get_freshness_info(&self, id: &str) -> Result<Option<(String, bool, String)>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT content_hash, protected, COALESCE(updated_at, '') FROM nodes WHERE id = ?1",
            )?;
            let mut rows = stmt.query(params![id])?;
            if let Some(row) = rows.next()? {
                Ok(Some((
                    row.get::<_, String>(0).unwrap_or_default(),
                    row.get::<_, i32>(1)? != 0,
                    row.get::<_, String>(2).unwrap_or_default(),
                )))
            } else {
                Ok(None)
            }
        })
    }

    /// Save an embedding for a node with model metadata.
    pub async fn save_embedding(&self, node_id: &str, embedding: &[f32], model_name: &str, model_hash: Option<&str>) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let bytes: Vec<u8> = embedding.iter().flat_map(|f| f.to_le_bytes().to_vec()).collect();
            let dimensions = embedding.len() as i32;
            conn.execute(
                "INSERT INTO node_embeddings (node_id, embedding, model_name, model_hash, dimensions)
                 VALUES (?1, ?2, ?3, ?4, ?5)
                 ON CONFLICT(node_id) DO UPDATE SET
                    embedding = excluded.embedding,
                    model_name = excluded.model_name,
                    model_hash = excluded.model_hash,
                    dimensions = excluded.dimensions",
                params![node_id, bytes, model_name, model_hash, dimensions],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Get embedding for a node.
    pub async fn get_node_embedding(&self, node_id: &str) -> Result<Option<Vec<f32>>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare("SELECT embedding FROM node_embeddings WHERE node_id = ?1")?;
            let mut rows = stmt.query(params![node_id])?;
            if let Some(row) = rows.next()? {
                let bytes: Vec<u8> = row.get(0)?;
                let vector: Vec<f32> = bytes.chunks_exact(4)
                    .map(|chunk| f32::from_le_bytes(chunk.try_into().expect("chunk should be exactly 4 bytes")))
                    .collect();
                return Ok(Some(vector));
            }
            Ok(None)
        })
    }

    /// Get the embedding model_name for a node, if one exists.
    pub async fn get_node_embedding_model(&self, node_id: &str) -> Result<Option<String>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT model_name FROM node_embeddings WHERE node_id = ?1 LIMIT 1"
            )?;
            let mut rows = stmt.query(params![node_id])?;
            if let Some(row) = rows.next()? {
                let name: Option<String> = row.get(0)?;
                Ok(name)
            } else {
                Ok(None)
            }
        })
    }

    /// Get node IDs with missing or outdated embeddings.
    pub async fn get_stale_embeddings(&self, current_model: &str, current_hash: Option<&str>) -> Result<Vec<String>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT n.id FROM nodes n
                 LEFT JOIN node_embeddings e ON n.id = e.node_id
                 WHERE e.node_id IS NULL
                    OR e.model_name != ?1
                    OR (e.model_hash IS NOT NULL AND ?2 IS NOT NULL AND e.model_hash != ?2)"
            )?;
            let rows = stmt.query_map(params![current_model, current_hash], |row| row.get(0))?;
            let mut results = Vec::new();
            for res in rows { results.push(res?); }
            Ok(results)
        })
    }

    /// Get nodes with embeddings that are marked conflicted.
    pub async fn get_conflicted_embeddings(&self) -> Result<Vec<(String, Vec<f32>)>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT e.node_id, e.embedding FROM node_embeddings e
                 JOIN nodes n ON e.node_id = n.id WHERE n.conflicted = 1"
            )?;
            let rows = stmt.query_map([], |row| {
                let node_id: String = row.get(0)?;
                let bytes: Vec<u8> = row.get(1)?;
                let vector: Vec<f32> = bytes.chunks_exact(4)
                    .map(|chunk| f32::from_le_bytes(chunk.try_into().expect("chunk should be exactly 4 bytes")))
                    .collect();
                Ok((node_id, vector))
            })?;
            let mut results = Vec::new();
            for res in rows {
                let (node_id, vector) = res?;
                results.push((node_id, vector));
            }
            Ok(results)
        })
    }

    /// Search nodes by topic_key.
    pub async fn search_by_topic(&self, topic: &str) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance
                 FROM nodes WHERE topic_key = ?1 ORDER BY weight DESC",
            )?;
            let rows = stmt.query_map(params![topic], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for node in rows { results.push(node?); }
            Ok(results)
        })
    }

    /// Get all nodes marked conflicted.
    pub async fn get_all_conflicted(&self) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance
                 FROM nodes WHERE conflicted = 1 ORDER BY updated_at DESC",
            )?;
            let rows = stmt.query_map([], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for node in rows { results.push(node?); }
            Ok(results)
        })
    }

    /// Mark a node as conflicted or resolved.
    pub async fn mark_conflicted(&self, id: &str, conflicted: bool) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let val = if conflicted { 1 } else { 0 };
            info!("SilvaDB: Marking node '{}' conflicted={}", id, conflicted);
            conn.execute(
                "UPDATE nodes SET conflicted = ?2, updated_at = CURRENT_TIMESTAMP WHERE id = ?1",
                params![id, val],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Set node protection status (immune to decay).
    pub async fn set_protected(&self, id: &str, protected: bool) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let val = if protected { 1 } else { 0 };
            info!("SilvaDB: Setting node '{}' protection={}", id, protected);
            conn.execute(
                "UPDATE nodes SET protected = ?2, updated_at = CURRENT_TIMESTAMP WHERE id = ?1",
                params![id, val],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Set node status metadata field.
    pub async fn set_status(&self, id: &str, status: &str) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            conn.execute(
                "UPDATE nodes SET metadata = json_set(COALESCE(metadata, '{}'), '$.status', ?2) WHERE id = ?1",
                params![id, status],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Reinforce a node's weight (multiply, cap at 10.0).
    pub async fn reinforce_node(&self, id: &str, multiplier: f64) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            conn.execute(
                "UPDATE nodes SET weight = MIN(weight * ?2, 10.0), conflicted = 0, updated_at = CURRENT_TIMESTAMP WHERE id = ?1",
                params![id, multiplier],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Set node weight directly.
    pub async fn set_weight(&self, id: &str, weight: f64) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            conn.execute(
                "UPDATE nodes SET weight = ?2, updated_at = CURRENT_TIMESTAMP WHERE id = ?1",
                params![id, weight],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Manual weight decay using half-life exponential formula.
    /// T_half = 14 days = 1_209_600 seconds.
    /// Decay a node using FSRS retrievability.
    /// Weight is derived from retrievability: R=2^(-elapsed_days / fsrs_stability).
    /// The node's fsrs_stability is also slightly reduced (passive decay).
    pub async fn decay_node(&self, id: &str, elapsed_secs: i64) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let elapsed_days = (elapsed_secs as f64 / 86400.0).max(0.0);

            let result: Result<(f64, f64, i64), _> = conn.query_row(
                "SELECT fsrs_stability, fsrs_difficulty, fsrs_last_review FROM nodes WHERE id = ?1",
                params![id],
                |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
            );
            if let Ok((stability, difficulty, last_review)) = result {
                let item = tylluan_fsrs::FsrsItem::with_params(stability, difficulty, last_review);
                let r = item.retrievability(elapsed_days);
                let new_weight = (r * 0.99 + 0.01).max(0.01);
                // Passive stability decay: -5% per 30 days
                let decayed_stability = (stability * 0.95_f64.powf(elapsed_days / 30.0))
                    .max(tylluan_fsrs::MIN_STABILITY_DAYS);
                conn.execute(
                    "UPDATE nodes SET weight = ?1, fsrs_stability = ?2, updated_at = CURRENT_TIMESTAMP WHERE id = ?3",
                    params![new_weight, decayed_stability, id],
                )?;
            }
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Detect communities (Louvain) and persist to node_communities.
    pub async fn detect_communities(&self) -> Result<HashMap<String, usize>> {
        let nodes = self.get_nodes_limited(1000, 0.0).await?;
        let edges = self.get_all_edges().await?;
        let node_ids: Vec<String> = nodes.iter().map(|n| n.id.clone()).collect();
        let mut graph = WeightedGraph::new(node_ids);
        for edge in edges {
            let source = edge.get("source").and_then(|v| v.as_str()).unwrap_or_default().to_string();
            let target = edge.get("target").and_then(|v| v.as_str()).unwrap_or_default().to_string();
            let weight = edge.get("weight").and_then(|v| v.as_f64()).unwrap_or(1.0);
            if !source.is_empty() && !target.is_empty() {
                graph.add_edge(&source, &target, weight);
            }
        }
        let communities = graph.find_communities();
        tokio::task::block_in_place(|| {
            let mut conn = self.conn.blocking_lock();
            // M31 audit fix: node_communities and nodes.cluster_id are two
            // separate tables updated in a loop -- a crash mid-loop left them
            // inconsistent (some nodes tagged in one table, not the other).
            let tx = conn.transaction()?;
            {
                let mut stmt = tx.prepare(
                    "INSERT INTO node_communities (node_id, cluster_id, updated_at)
                     VALUES (?1, ?2, CURRENT_TIMESTAMP)
                     ON CONFLICT(node_id) DO UPDATE SET cluster_id = excluded.cluster_id, updated_at = CURRENT_TIMESTAMP"
                )?;
                for (node_id, cluster_id) in &communities {
                    stmt.execute(params![node_id, *cluster_id as i64])?;
                }
                let mut stmt_node = tx.prepare("UPDATE nodes SET cluster_id = ?2 WHERE id = ?1")?;
                for (node_id, cluster_id) in &communities {
                    stmt_node.execute(params![node_id, *cluster_id as i64])?;
                }
            }
            tx.commit()?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(communities)
    }

    /// Get community ID for a node.
    pub async fn get_node_community(&self, node_id: &str) -> Result<Option<usize>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let res: Option<i64> = conn.query_row(
                "SELECT cluster_id FROM node_communities WHERE node_id = ?1",
                params![node_id], |r| r.get(0)
            ).ok();
            Ok(res.map(|c| c as usize))
        })
    }

    /// Returns true if two nodes have embedding cosine similarity >= threshold.
    pub async fn nodes_are_similar(&self, id_a: &str, id_b: &str, threshold: f64) -> Result<bool> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let emb_a: Option<Vec<u8>> = conn.query_row(
                "SELECT embedding FROM node_embeddings WHERE node_id = ?1 LIMIT 1",
                params![id_a], |r| r.get(0)
            ).ok();
            let emb_b: Option<Vec<u8>> = conn.query_row(
                "SELECT embedding FROM node_embeddings WHERE node_id = ?1 LIMIT 1",
                params![id_b], |r| r.get(0)
            ).ok();
            match (emb_a, emb_b) {
                (Some(a), Some(b)) => Ok(super::dream_cosine(&a, &b) >= threshold),
                _ => Ok(false),
            }
        })
    }

    /// Merge `src` into `dst`: re-point all edges, then delete src.
    pub async fn merge_node_into(&self, src: &str, dst: &str) -> Result<()> {
        tokio::task::block_in_place(|| {
            let mut conn = self.conn.blocking_lock();
            // M31 audit fix: 6 sequential statements re-pointing edges then
            // deleting src -- a crash mid-sequence left a "phantom" node with
            // some edges re-pointed and others still dangling on the deleted id.
            let tx = conn.transaction()?;
            // OR IGNORE: dst may already hold an identical edge (PK source,target,type) —
            // without it one collision aborts the whole merge (root cause of dedup never merging).
            tx.execute("UPDATE OR IGNORE edges SET source = ?2 WHERE source = ?1 AND target != ?2", params![src, dst])?;
            tx.execute("UPDATE OR IGNORE edges SET target = ?2 WHERE target = ?1 AND source != ?2", params![src, dst])?;
            // Drop src edges that collided (left in place by OR IGNORE) plus self-loops
            tx.execute("DELETE FROM edges WHERE source = ?1 OR target = ?1", params![src])?;
            tx.execute("DELETE FROM edges WHERE source = target", params![])?;
            tx.execute("DELETE FROM node_embeddings WHERE node_id = ?1", params![src])?;
            tx.execute("DELETE FROM nodes WHERE id = ?1", params![src])?;
            tx.commit()?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Flag source nodes conflicted when they have >1 distinct target for the same predicate.
    /// M35: applies temporal supersession — the edge with the most recent valid_from is the
    /// current truth; older edges get valid_until set to the superseding edge's valid_from
    /// (they remain in the DB but are no longer "current"). If ≥2 edges have the same
    /// valid_from and it's the maximum for the group, that is a genuine tie and the node
    /// is marked conflicted = 1 for human/agent review.
    pub async fn flag_contradiction_nodes(&self) -> Result<usize> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();

            // Fetch all edges (except related_to) ordered by source, type, valid_from
            let mut stmt = conn.prepare(
                "SELECT source, type, target, valid_from FROM edges
                 WHERE type != 'related_to'
                 ORDER BY source, type, valid_from ASC NULLS LAST"
            )?;
            let rows: Vec<(String, String, String, Option<i64>)> = stmt.query_map([], |row| {
                Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?))
            })?.filter_map(|r| r.ok()).collect();

            // Group edges by (source, type)
            let mut groups: EdgeGroupMap = std::collections::HashMap::new();
            for (src, typ, tgt, vf) in &rows {
                groups.entry((src.clone(), typ.clone())).or_default().push((tgt.clone(), *vf));
            }

            let mut conflict_count = 0usize;

            for ((src, typ), edge_list) in &groups {
                // Only process groups with >1 distinct target
                let distinct_targets: std::collections::HashSet<&str> =
                    edge_list.iter().map(|(t, _)| t.as_str()).collect();
                if distinct_targets.len() <= 1 { continue; }

                // Find max valid_from (NULLs treated as lowest)
                let max_vf = edge_list.iter()
                    .filter_map(|(_, vf)| *vf)
                    .max();

                match max_vf {
                    None => {
                        // All NULL valid_from — no temporal signal, flag as conflicted
                        conn.execute(
                            "UPDATE nodes SET conflicted = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?1 AND conflicted = 0",
                            params![src],
                        )?;
                        conflict_count += 1;
                    }
                    Some(max) => {
                        // Count edges at max valid_from
                        let at_max_count = edge_list.iter()
                            .filter(|(_, vf)| *vf == Some(max))
                            .count();

                        if at_max_count > 1 {
                            // Genuine tie — two edges claim the same most-recent time
                            conn.execute(
                                "UPDATE nodes SET conflicted = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?1 AND conflicted = 0",
                                params![src],
                            )?;
                            conflict_count += 1;
                        }

                        // Supersede older edges (valid_from < max OR NULL) — set valid_until = max
                        for (tgt, vf) in edge_list {
                            if *vf != Some(max) {
                                conn.execute(
                                    "UPDATE edges SET valid_until = ?1
                                     WHERE source = ?2 AND target = ?3 AND type = ?4 AND valid_until IS NULL",
                                    params![max, src, tgt, typ],
                                )?;
                            }
                        }
                    }
                }
            }

            Ok::<usize, anyhow::Error>(conflict_count)
        })
    }

    /// Mark a node as protected so it never decays or gets pruned.
    pub async fn protect_node(&self, id: &str) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            conn.execute(
                "UPDATE nodes SET protected = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?1",
                params![id],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Delete a node and all its edges/traces/embeddings. Returns false if protected.
    pub async fn delete_node(&self, id: &str) -> Result<bool> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let protected: bool = conn.query_row(
                "SELECT protected FROM nodes WHERE id = ?1",
                params![id], |r| r.get(0),
            ).unwrap_or(false);
            if protected { return Ok(false); }
            let fts_rowid: Option<i64> = conn.query_row(
                "SELECT rowid FROM nodes WHERE id = ?1",
                params![id], |r| r.get(0),
            ).ok();
            let tx = conn.unchecked_transaction()?;
            tx.execute("DELETE FROM edges WHERE source = ?1 OR target = ?1", params![id])?;
            tx.execute("DELETE FROM node_traces WHERE node_id = ?1", params![id])?;
            tx.execute("DELETE FROM node_embeddings WHERE node_id = ?1", params![id])?;
            let deleted = tx.execute("DELETE FROM nodes WHERE id = ?1", params![id])?;
            tx.commit()?;
            if let Some(rid) = fts_rowid {
                conn.execute("DELETE FROM nodes_fts WHERE rowid = ?1", params![rid]).ok();
            }
            Ok(deleted > 0)
        })
    }

    /// Get list of protected nodes.
    pub async fn get_protected_nodes(&self, limit: usize) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance
                 FROM nodes WHERE protected = 1 ORDER BY updated_at DESC LIMIT ?1",
            )?;
            let rows = stmt.query_map(params![limit as i64], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for node in rows { results.push(node?); }
            Ok(results)
        })
    }

    /// Apply lazy Ebbinghaus decay to a single node based on elapsed time.
    pub async fn apply_node_decay(&self, node_id: &str) -> Result<f64> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let result: std::result::Result<(f64, Option<i64>), rusqlite::Error> = conn.query_row(
                "SELECT weight, last_touched FROM nodes WHERE id = ?1",
                params![node_id],
                |row| Ok((row.get(0)?, row.get(1)?)),
            );
            let (weight, last_touched) = match result {
                Ok((w, Some(lt))) => (w, lt),
                Ok((w, None)) => return Ok(w),
                Err(_) => return Err(anyhow::anyhow!("Node not found: {node_id}")),
            };
            let now = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs() as i64;
            let elapsed_secs = (now - last_touched) as f64;
            let hours = elapsed_secs / 3600.0;
            if hours < 1.0 { return Ok(weight); }

            let trace_count: i64 = conn.query_row(
                "SELECT COUNT(*) FROM node_traces WHERE node_id = ?1 AND touched_at >= ?2",
                params![node_id, now - 86400], |r| r.get(0),
            ).unwrap_or(0);
            let heat = (trace_count as f64 / 240.0).min(1.0);
            let lambda = 0.05;
            let in_degree: i64 = conn.query_row(
                "SELECT COUNT(*) FROM edges WHERE target = ?1",
                params![node_id], |r| r.get(0),
            ).unwrap_or(0);
            let protection = 1.0 / (1.0 + (in_degree as f64).ln().max(0.0));
            let mut lambda_eff = lambda * protection * (1.0 - 0.3 * heat);
            let rejected_count: i64 = conn.query_row(
                "SELECT COUNT(*) FROM node_traces WHERE node_id = ?1 AND trace_type = 'rejected' AND touched_at >= ?2",
                params![node_id, now - 86400], |r| r.get(0),
            ).unwrap_or(0);
            if rejected_count > 5 { lambda_eff *= 3.0; }
            // Adaptive decay by node type prefix
            let type_multiplier: f64 = if node_id.starts_with("lesson:intent:") { 3.0 }
                else if node_id.starts_with("concept:") { 0.33 }
                else { 1.0 };
            lambda_eff *= type_multiplier;
            let new_weight = weight * (-lambda_eff * hours).exp();
            let salience = new_weight * (1.0 + (trace_count as f64 + 1.0).ln() * 0.1);
            conn.execute(
                "UPDATE nodes SET weight = ?1, salience_score = ?2 WHERE id = ?3",
                params![new_weight, salience, node_id],
            )?;
            Ok(new_weight)
        })
    }

    /// Get node access traces (stigmergy).
    pub async fn get_node_traces(&self, node_id: &str, limit: usize) -> Result<Vec<NodeTrace>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT node_id, agent_id, touched_at, trace_type FROM node_traces WHERE node_id = ?1 ORDER BY touched_at DESC LIMIT ?2",
            )?;
            let rows = stmt.query_map(params![node_id, limit as i64], |row| {
                Ok(NodeTrace {
                    node_id: row.get(0)?, agent_id: row.get(1)?,
                    touched_at: row.get(2)?, trace_type: row.get(3)?,
                })
            })?;
            let mut results = Vec::new();
            for row in rows { results.push(row?); }
            Ok(results)
        })
    }

    /// Count traces for a node since the given unix timestamp.
    pub async fn get_trace_count_since(&self, node_id: &str, since_unix: i64) -> Result<u32> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let count: i64 = conn.query_row(
                "SELECT COUNT(*) FROM node_traces WHERE node_id = ?1 AND touched_at >= ?2",
                params![node_id, since_unix], |row| row.get(0),
            )?;
            Ok(count as u32)
        })
    }

    /// Count traces of a specific type for a node since a unix timestamp.
    pub async fn get_trace_count_by_type(&self, node_id: &str, trace_type: &str, since_unix: i64) -> Result<u32> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let count: i64 = conn.query_row(
                "SELECT COUNT(*) FROM node_traces WHERE node_id = ?1 AND trace_type = ?2 AND touched_at >= ?3",
                params![node_id, trace_type, since_unix], |row| row.get(0),
            )?;
            Ok(count as u32)
        })
    }

    /// Right to be forgotten: delete all nodes and edges for an agent.
    pub async fn forget_agent(&self, agent_id: &str) -> Result<usize> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let deleted = conn.execute(
                "DELETE FROM nodes WHERE metadata LIKE ?",
                params![format!("%\"agent\":\"{}\"%", agent_id)],
            )?;
            conn.execute(
                "DELETE FROM edges WHERE source NOT IN (SELECT id FROM nodes) OR target NOT IN (SELECT id FROM nodes)",
                [],
            )?;
            info!("SilvaDB: Right to be forgotten. Agent '{}' removed {} nodes.", agent_id, deleted);
            Ok(deleted)
        })
    }

    /// Mark node as private (not shared in collective memory).
    pub async fn make_private(&self, node_id: &str) -> Result<()> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            conn.execute(
                "UPDATE nodes SET metadata = json_set(COALESCE(metadata, '{}'), '$.private', true) WHERE id = ?1",
                params![node_id],
            )?;
            Ok::<(), anyhow::Error>(())
        })?;
        Ok(())
    }

    /// Get total node count.
    pub async fn node_count(&self) -> Result<usize> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let count: i64 = conn.query_row("SELECT COUNT(*) FROM nodes", [], |row| row.get(0))?;
            Ok(count as usize)
        })
    }

    /// Count nodes by type. Used by drift guard probe.
    pub async fn count_by_type(&self, node_type: &str) -> Result<usize> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let count: i64 = conn.query_row(
                "SELECT COUNT(*) FROM nodes WHERE type = ?1",
                params![node_type],
                |row| row.get(0),
            )?;
            Ok(count as usize)
        })
    }

    /// Fetch nodes matching any of the given types, ordered by weight DESC.
    pub async fn get_nodes_by_types(&self, types: &[&str], limit: usize) -> Result<Vec<GraphNode>> {
        let placeholders: String = types.iter().enumerate()
            .map(|(i, _)| format!("?{}", i + 1))
            .collect::<Vec<_>>().join(", ");
        let sql = format!(
            "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, \
             created_at, updated_at, shareable, valid_from, valid_until, provenance \
             FROM nodes WHERE type IN ({placeholders}) ORDER BY weight DESC LIMIT {limit}"
        );
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(&sql)?;
            let rows = stmt.query_map(
                rusqlite::params_from_iter(types.iter()),
                |row| Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                }),
            )?;
            rows.collect::<Result<Vec<_>, _>>().map_err(Into::into)
        })
    }

    /// Count nodes that have a non-empty topic_key.
    pub async fn count_nodes_with_topic_key(&self) -> Result<usize> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let count: i64 = conn.query_row(
                "SELECT COUNT(*) FROM nodes WHERE topic_key IS NOT NULL AND topic_key != ''",
                [], |row| row.get(0),
            )?;
            Ok(count as usize)
        })
    }

    /// Count nodes that have a stored embedding in node_embeddings table.
    pub async fn count_nodes_with_embedding(&self) -> Result<usize> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let count: i64 = conn.query_row(
                "SELECT COUNT(DISTINCT node_id) FROM node_embeddings",
                [], |row| row.get(0),
            )?;
            Ok(count as usize)
        })
    }

    /// Create or update agent identity node.
    pub async fn update_agent_identity(&self, agent_id: &str, agent_name: &str, session_count: usize, first_seen: &str) -> Result<()> {
        let node_id = format!("agent:{agent_id}");
        let metadata = serde_json::json!({
            "agent": agent_id, "name": agent_name,
            "sessions": session_count, "first_seen": first_seen,
            "last_active": chrono::Utc::now().to_rfc3339()
        }).to_string();
        self.upsert_node(&node_id, "identity", &format!("Agent {agent_name} ({session_count} sessions)"), &metadata).await?;
        info!("SilvaDB: Agent identity updated for '{}' ({} sessions)", agent_name, session_count);
        Ok(())
    }

    /// Get agent identity node by agent_id.
    pub async fn get_agent_identity(&self, agent_id: &str) -> Result<Option<GraphNode>> {
        let node_id = format!("agent:{agent_id}");
        self.get_node(&node_id).await
    }

    /// Get N most recently updated nodes.
    pub async fn get_recent_nodes(&self, limit: usize) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance
                 FROM nodes ORDER BY updated_at DESC LIMIT ?1"
            )?;
            let rows = stmt.query_map(params![limit as i64], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for row in rows { results.push(row?); }
            Ok(results)
        })
    }

    /// Get all nodes (for export/visualization).
    pub async fn get_all_nodes(&self) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance FROM nodes"
            )?;
            let rows = stmt.query_map([], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for row in rows { results.push(row?); }
            Ok(results)
        })
    }

    /// Get top-N nodes by weight above a minimum threshold.
    pub async fn get_nodes_limited(&self, limit: usize, min_weight: f64) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance \
                 FROM nodes WHERE weight >= ?1 ORDER BY weight DESC, id DESC LIMIT ?2"
            )?;
            let rows = stmt.query_map(rusqlite::params![min_weight, limit as i64], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for row in rows { results.push(row?); }
            Ok(results)
        })
    }

    /// J-8: fetch lightweight (id, type, content, owner_scope) rows whose owner_scope starts
    /// with `scope_prefix` (hierarchical prefix match — e.g. "user:alice" matches
    /// "user:alice/session:s1/agent:claude"). Returns tuples instead of `GraphNode` to avoid
    /// widening the struct's ~20 existing construction sites for this one filtered view.
    pub async fn get_nodes_by_scope_prefix(
        &self,
        scope_prefix: &str,
        limit: usize,
    ) -> Result<Vec<(String, String, String, Option<String>)>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, owner_scope FROM nodes \
                 WHERE owner_scope = ?1 OR owner_scope LIKE ?1 || '/%' \
                 ORDER BY weight DESC LIMIT ?2"
            )?;
            let rows = stmt.query_map(rusqlite::params![scope_prefix, limit as i64], |row| {
                Ok((
                    row.get::<_, String>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, String>(2)?,
                    row.get::<_, Option<String>>(3)?,
                ))
            })?;
            let mut results = Vec::new();
            for row in rows { results.push(row?); }
            Ok(results)
        })
    }

    /// Paginated node fetch ordered by id for stable export.
    pub async fn get_nodes_paginated(&self, limit: usize, offset: usize) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance \
                 FROM nodes ORDER BY id LIMIT ?1 OFFSET ?2"
            )?;
            let rows = stmt.query_map(rusqlite::params![limit as i64, offset as i64], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? == 1,
                    conflicted: row.get::<_, i32>(6)? == 1,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for row in rows { results.push(row?); }
            Ok(results)
        })
    }

    /// Query nodes by exact type and content prefix.
    pub async fn get_nodes_by_type_and_prefix(&self, node_type: &str, content_prefix: &str, limit: usize) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let pattern = format!("{content_prefix}%");
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance \
                 FROM nodes WHERE type = ?1 AND content LIKE ?2 ORDER BY weight DESC, id DESC LIMIT ?3"
            )?;
            let rows = stmt.query_map(rusqlite::params![node_type, pattern, limit as i64], |row| {
                Ok(GraphNode {
                    id: row.get(0)?, node_type: row.get(1)?, content: row.get(2)?,
                    metadata: row.get(3)?, weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? != 0,
                    conflicted: row.get::<_, i32>(6)? != 0,
                    topic_key: row.get(7)?, created_at: read_timestamp(row, 8)?, updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            let mut results = Vec::new();
            for row in rows { results.push(row?); }
            Ok(results)
        })
    }

    pub async fn get_identity_nodes(&self) -> Result<Vec<GraphNode>> {
        tokio::task::block_in_place(|| {
            let conn = self.conn.blocking_lock();
            let mut stmt = conn.prepare(
                "SELECT id, type, content, metadata, weight, protected, conflicted, topic_key, created_at, updated_at, shareable, valid_from, valid_until, provenance FROM nodes WHERE type = 'identity'"
            )?;
            let rows = stmt.query_map([], |row| {
                Ok(GraphNode {
                    id: row.get(0)?,
                    node_type: row.get(1)?,
                    content: row.get(2)?,
                    metadata: row.get(3)?,
                    weight: row.get(4)?,
                    protected: row.get::<_, i32>(5)? == 1,
                    conflicted: row.get::<_, i32>(6)? == 1,
                    topic_key: row.get(7)?,
                    created_at: read_timestamp(row, 8)?,
                    updated_at: read_timestamp(row, 9)?,
                    shareable: row.get::<_, i32>(10)? != 0,
                    content_hash: "".to_string(),
                    valid_from: row.get(11)?, valid_until: row.get(12)?,
                    provenance: row.get(13)?,
                    last_touched: Utc::now(),
                })
            })?;
            
            let mut results = Vec::new();
            for node in rows.flatten() {
                results.push(node);
            }
            Ok(results)
        })
    }
}

/// Build contextual text for embedding (Contextual Retrieval pattern).
/// Prepends document origin metadata before the content so the embedding
/// captures WHERE the chunk came from, not just WHAT it says.
/// Offline-friendly: uses only metadata already stored in the node — no LLM call.
pub fn build_contextual_text(metadata_json: &str, content: &str) -> String {
    let Ok(meta) = serde_json::from_str::<serde_json::Value>(metadata_json) else {
        return content.to_string();
    };
    let source = meta.get("source_file")
        .or_else(|| meta.get("source"))
        .or_else(|| meta.get("file"))
        .and_then(|v| v.as_str());
    let heading = meta.get("heading_path")
        .or_else(|| meta.get("section"))
        .or_else(|| meta.get("heading"))
        .and_then(|v| v.as_str());
    match (source, heading) {
        (Some(s), Some(h)) => format!("[{s} > {h}]\n{content}"),
        (Some(s), None)    => format!("[{s}]\n{content}"),
        _                  => content.to_string(),
    }
}
